# This file is automatically generated by setup.py

from customization import *

appCustomization = Customize(appname = "App Name Here",
                          appsource = "URL where app's .zip is sourced",
                          appversion = "App Version Here",
                          appicon = resource_path("icon.ico"))